spring:
  application:
    name: orders-service

  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/orders?authSource=admin

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    exchange-verify-payment: verify-payment-fanout
    exchange-approved-payment: payment-approved-order-queue
    delivery-ready-update: delivery-shipped-update-queue

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${random.value}