spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/orders?authSource=admin

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    exchange-payment: verify-payment-fanout

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"

server:
  port: 8082

customers:
  url: http://localhost:8080/api/customers
restaurants:
  url: http://localhost:8081/api/restaurants