version: '3.9'

networks:
  database-network:
    driver: bridge

services:
  customer_postgres:
    image: postgres:16
    container_name: customers_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: customers_db
    ports:
      - "5432:5432"
    networks:
      - database-network
    volumes:
      - ./customers_data:/var/lib/postgresql/data

  restaurants_postgres:
    image: postgres:16
    container_name: restaurants_database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: restaurants_db
    ports:
      - "5433:5432"
    networks:
      - database-network
    volumes:
      - ./restaurants_data:/var/lib/postgresql/data

  orders_mongodb:
    image: mongo:7
    container_name: orders_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    networks:
      - database-network
    volumes:
      - ./mongodb_data:/data/db

  payments_mongodb:
      image: mongo:7
      container_name: payments_mongodb
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin123
      ports:
        - "27018:27017"
      networks:
        - database-network
      volumes:
        - ./payments_data:/data/db

  redis:
    image: redis:8
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    networks:
      - database-network
    command: ["redis-server", "--appendonly", "yes"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - database-network
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin