spring:
  application:
      name: payment-service

  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27018/payments?authSource=admin

  rabbitmq:
    password: admin123
    username: admin
    host: localhost
    port: 5672
    subscriber:
      payment-queue: verify-payment-queue
    publisher:
      payment-exchange: approved-payment-fanout


  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"

server:
  port: 8084