spring:
  application:
    name: authentication-service

  output:
    ansi:
      enabled: ALWAYS

  keycloak:
    token-url: http://localhost:8081/realms/delivery-system-realm/protocol/openid-connect/token
    client-id: api-gateway-systemdelivery
    client-secret: JSgtF9WAQXPMGr8b5IqbELnwFNquJALx

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: REDIS

  rabbitmq:
    username: admin
    password: admin123
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"

server:
  port: 0
