spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/orders?authSource=admin

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"

server:
  port: 8082
