version: '3.9'

networks:
  database-network:
    driver: bridge

services:
  customer_postgres:
    image: postgres:16
    container_name: customers_database
    restart: always
    environment:
      POSTGRES_USER: ${CUSTOMERS_DB_USER}
      POSTGRES_PASSWORD: ${CUSTOMERS_DB_PASSWORD}
      POSTGRES_DB: ${CUSTOMERS_DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - database-network
    volumes:
      - ./infra/databases/customers_data:/var/lib/postgresql/data

  restaurants_postgres:
    image: postgres:16
    container_name: restaurants_database
    restart: always
    environment:
      POSTGRES_USER: ${RESTAURANTS_DB_USER}
      POSTGRES_PASSWORD: ${RESTAURANTS_DB_PASSWORD}
      POSTGRES_DB: ${RESTAURANTS_DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - database-network
    volumes:
      - ./infra/databases/restaurants_data:/var/lib/postgresql/data

  delivery_postgres:
    image: postgres:16
    container_name: deliveries_database
    restart: always
    environment:
      POSTGRES_USER: ${DELIVERIES_DB_USER}
      POSTGRES_PASSWORD: ${DELIVERIES_DB_PASSWORD}
      POSTGRES_DB: ${DELIVERIES_DB_NAME}
    ports:
      - "5434:5432"
    networks:
      - database-network
    volumes:
      - ./infra/databases/deliveries_data:/var/lib/postgresql/data

  orders_mongodb:
    image: mongo:7
    container_name: orders_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ORDERS_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ORDERS_MONGO_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - database-network
    volumes:
      - ./infra/databases/mongodb_data:/data/db

  payments_mongodb:
    image: mongo:7
    container_name: payments_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PAYMENTS_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PAYMENTS_MONGO_PASSWORD}
    ports:
      - "27018:27017"
    networks:
      - database-network
    volumes:
      - ./infra/databases/payments_data:/data/db

  redis:
    image: redis:8
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    networks:
      - database-network
    command: ["redis-server", "--appendonly", "yes"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - database-network
    volumes:
      - ./infra/databases/pgadmin_data:/var/lib/pgadmin
