version: '3.9'

networks:
  security-network:
    driver: bridge

services:
  postgres:
    image: postgres:16
    container_name: postgres_keycloak
    restart: always
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - ./infra/security/postgres_data:/var/lib/postgresql/data
    networks:
      - security-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.2
    container_name: keycloak_server
    restart: always
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: ${KEYCLOAK_POSTGRES_HOST}
      KC_DB_URL_DATABASE: ${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: localhost
    ports:
      - "8081:8080"
    command: start-dev
    depends_on:
      - postgres
    networks:
      - security-network
    volumes:
      - ./infra/security/keycloak_data:/opt/keycloak/data