spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://localhost:5434/delivery_db
    username: admin
    password: admin123

  rabbitmq:
    port: 5672
    host: localhost
    username: admin
    password: admin123
    delivery-queue: payment-approved-delivery-queue
  clients:
    order-service:
        url: http://localhost:8082/api/orders

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"

server:
  port: 8085
