spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://localhost:5434/delivery_db
    username: admin
    password: admin123

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  pattern:
    console: "%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n"

server:
  port: 8085
