name: System Delivery Eureka Service

on:
  push:
      branches:
        - main
      paths:
        - 'infrastructure-service/eureka/**'
        - '.github/workflows/eureka-service-prod.yml'

jobs:
    build:
      runs-on: self-hosted
      defaults:
        run:
          working-directory: ./infrastructure-service/eureka
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: '21'
            cache: 'maven'

        - name: Build project
          run: mvn clean install

        - name: Login docker
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          working-directory: .

        - name: Build docker image
          run: docker build -t caiquepirs/eureka-service .

        - name: Publish image
          run: docker push caiquepirs/eureka-service

    deploy:
      needs: build
      runs-on: self-hosted
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Pull image docker
          run: docker pull caiquepirs/eureka-service

        - name: Create docker file
          run: |
            echo "${{ secrets.DOCKER_ENV_FILE }}" > .env

        - name: Run docker compose
          run: | 
            docker compose up -d --no-deps eureka-service
            docker image prune -f